default_language_version:
  python: python3

ci:
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit suggestions"
  autoupdate_schedule: quarterly
  # submodules: true

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

  #- repo: https://github.com/executablebooks/mdformat
  #  rev: 0.7.17
  #  hooks:
  #    - id: mdformat
  #      additional_dependencies:
  #        - mdformat-gfm
  #        - mdformat-black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      # try to fix what is possible
      - id: ruff
        args: ["--fix"]
      # perform formatting updates
      - id: ruff-format
