name: "GitHub Dependents Info"
author: "Nicolas Vuillamy"
description: "Generates a markdown file with all repositories that have dependencies with the current GitHub repository package (s)"
inputs:
  repo:
    description: "Owner and name of the repository (example: nvuillam/node-sarif-builder)"
    required: true
  outputrepo:
    description: "Owner and name of the output repository, if different from repo (example: nvuillam/node-sarif-builder)"
    required: false
    default: ""
  markdownfile:
    description: "Path and name of the output markdown file"
    required: false
    default: "docs/github-dependents-info.md"
  badgemarkdownfile:
    description: "Path and name of the file where to replace badges (example: README.md). Must contain tags <!-- gh-dependents-info-used-by-start --><!-- gh-dependents-info-used-by-end -->"
    required: false
    default: README.md
  docurl:
    description: "Custom URL to use for the badges hyperlink (defaults to generated markdown)"
    required: false
    default: ""
  markdownbadgecolor:
    description: "Color of the generated markdown badge"
    required: false
    default: informational
  sort:
    description: "Sort criteria: stars (default) or name"
    required: false
    default: stars
  minstars:
    description: "Minimum number of stars to appear in the results"
    required: false
    default: "0"
  timedelay:
    description: "Delay in seconds between GitHub requests"
    required: false
    default: "0.1"
  csvdirectory:
    description: "Directory path where CSV files should be written"
    required: false
    default: ""
  mergepackages:
    description: "If multiple packages, merge them into a single result when true"
    required: false
    default: "false"
  json:
    description: "Set to true to emit JSON output"
    required: false
    default: "false"
  verbose:
    description: "Set to true to enable verbose logging"
    required: false
    default: "false"
  overwrite:
    description: "Set to true to overwrite existing CSV progress files"
    required: false
    default: "false"
  owner:
    description: "Filter dependent repositories by owner (example: oxsecurity)"
    required: false
    default: ""
  max-scraped-pages:
    description: "Maximum number of pages to scrape per package (0 means no limit)"
    required: false
    default: "0"
  pagination:
    description: "Enable pagination to split results into multiple files"
    required: false
    default: "true"
  page-size:
    description: "Number of results per page when pagination is enabled"
    required: false
    default: "500"

runs:
  using: "docker"
  image: "docker://nvuillam/github-dependents-info:v2.0.1"
  entrypoint: /bin/sh
  args:
    - -c
    - |
      set -euo pipefail

      max_scraped_pages=$(printenv 'INPUT_MAX-SCRAPED-PAGES' 2>/dev/null || true)
      page_size=$(printenv 'INPUT_PAGE-SIZE' 2>/dev/null || true)

      set -- github-dependents-info "--repo=${INPUT_REPO}"

      if [ -n "${INPUT_OUTPUTREPO:-}" ]; then
        set -- "$@" "--outputrepo=${INPUT_OUTPUTREPO}"
      fi

      if [ -n "${INPUT_MARKDOWNFILE:-}" ]; then
        set -- "$@" "--markdownfile=${INPUT_MARKDOWNFILE}"
      fi

      if [ -n "${INPUT_BADGEMARKDOWNFILE:-}" ]; then
        set -- "$@" "--badgemarkdownfile=${INPUT_BADGEMARKDOWNFILE}"
      fi

      if [ -n "${INPUT_DOCURL:-}" ]; then
        set -- "$@" "--docurl=${INPUT_DOCURL}"
      fi

      if [ -n "${INPUT_MARKDOWNBADGECOLOR:-}" ]; then
        set -- "$@" "--markdownbadgecolor=${INPUT_MARKDOWNBADGECOLOR}"
      fi

      if [ -n "${INPUT_SORT:-}" ]; then
        set -- "$@" "--sort=${INPUT_SORT}"
      fi

      if [ -n "${INPUT_MINSTARS:-}" ]; then
        set -- "$@" "--minstars=${INPUT_MINSTARS}"
      fi

      if [ -n "${INPUT_TIMEDELAY:-}" ]; then
        set -- "$@" "--timedelay=${INPUT_TIMEDELAY}"
      fi

      if [ -n "${INPUT_CSVDIRECTORY:-}" ]; then
        set -- "$@" "--csvdirectory=${INPUT_CSVDIRECTORY}"
      fi

      if [ -n "${INPUT_OWNER:-}" ]; then
        set -- "$@" "--owner=${INPUT_OWNER}"
      fi

      if [ -n "$max_scraped_pages" ] && [ "$max_scraped_pages" != "0" ]; then
        set -- "$@" "--max-scraped-pages=${max_scraped_pages}"
      fi

      if [ "${INPUT_PAGINATION:-true}" = "false" ]; then
        set -- "$@" "--no-pagination"
      fi

      if [ -n "$page_size" ] && [ "$page_size" != "" ]; then
        set -- "$@" "--page-size=${page_size}"
      fi

      if [ "${INPUT_JSON:-false}" = "true" ]; then
        set -- "$@" "--json"
      fi

      if [ "${INPUT_MERGEPACKAGES:-false}" = "true" ]; then
        set -- "$@" "--mergepackages"
      fi

      if [ "${INPUT_VERBOSE:-false}" = "true" ]; then
        set -- "$@" "--verbose"
      fi

      if [ "${INPUT_OVERWRITE:-false}" = "true" ]; then
        set -- "$@" "--overwrite"
      fi

      exec "$@"

branding:
  icon: "users"
  color: "green"
