"""Tests for reuse of a previously generated AI summary (offline)"""

import types

import asyncio
import os
import sys

from github_dependents_info.gh_dependents_info import (
    LLM_SUMMARY_END_MARKER,
    LLM_SUMMARY_START_MARKER,
    GithubDependentsInfo,
)

PREVIOUS_SUMMARY = "**Acme** and **Globex** use this package.\n\n- **pytest** ecosystem"

LLM_ENV_VARS = [
    "OPENAI_API_KEY",
    "AZURE_OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "GEMINI_API_KEY",
    "GOOGLE_API_KEY",
    "MISTRAL_API_KEY",
    "COHERE_API_KEY",
    "GROQ_API_KEY",
]


def remove_llm_api_keys(monkeypatch):
    for env_var in LLM_ENV_VARS:
        monkeypatch.delenv(env_var, raising=False)


def build_markdown_with_summary(summary: str, with_markers: bool = True) -> str:
    lines = ["# Dependents stats for nvuillam/demo", ""]
    if with_markers:
        lines += [LLM_SUMMARY_START_MARKER, ""]
    lines += ["## Summary", "", summary, ""]
    if with_markers:
        lines += [LLM_SUMMARY_END_MARKER, ""]
    lines += [
        "[![](https://img.shields.io/static/v1?label=Used%20by&message=12)](https://github.com/nvuillam/demo)",
        "",
        "| Repository | Stars  |",
        "| :--------  | -----: |",
        "| [acme/foo](https://github.com/acme/foo) | 12 |",
        "",
        (
            "_Generated using [github-dependents-info]"
            "(https://github.com/nvuillam/github-dependents-info), "
            "by [Nicolas Vuillamy](https://github.com/nvuillam)_"
        ),
    ]
    return "\n".join(lines)


def test_extract_summary_with_markers():
    gh = GithubDependentsInfo("nvuillam/demo")
    md = build_markdown_with_summary(PREVIOUS_SUMMARY, with_markers=True)
    assert gh._extract_summary_from_markdown_content(md) == PREVIOUS_SUMMARY


def test_extract_summary_without_markers():
    """Markdown generated by a previous version, without summary markers"""
    gh = GithubDependentsInfo("nvuillam/demo")
    md = build_markdown_with_summary(PREVIOUS_SUMMARY, with_markers=False)
    assert gh._extract_summary_from_markdown_content(md) == PREVIOUS_SUMMARY


def test_extract_summary_when_none():
    gh = GithubDependentsInfo("nvuillam/demo")
    md = build_markdown_with_summary("", with_markers=False).replace("## Summary", "")
    assert gh._extract_summary_from_markdown_content(md) is None


def test_summary_reused_when_no_api_key(tmp_path, monkeypatch):
    """No LLM API key anymore: the summary of the previous run must be kept"""
    remove_llm_api_keys(monkeypatch)
    markdown_file = tmp_path / "dependents.md"
    markdown_file.write_text(build_markdown_with_summary(PREVIOUS_SUMMARY), encoding="utf-8")

    gh = GithubDependentsInfo("nvuillam/demo", markdown_file=str(markdown_file))
    asyncio.run(gh.maybe_generate_llm_summary())

    assert gh.llm_summary == PREVIOUS_SUMMARY
    assert gh.llm_summary_reused is True
    assert "## Summary" in gh._build_single_markdown()


def test_summary_reused_when_llm_call_fails(tmp_path, monkeypatch):
    """No credit left on the LLM provider: the summary of the previous run must be kept"""
    remove_llm_api_keys(monkeypatch)
    monkeypatch.setenv("OPENAI_API_KEY", "sk-fake")

    async def acompletion(*args, **kwargs):
        raise RuntimeError("Insufficient credit balance")

    fake_litellm = types.ModuleType("litellm")
    fake_litellm.acompletion = acompletion
    monkeypatch.setitem(sys.modules, "litellm", fake_litellm)

    markdown_file = tmp_path / "dependents.md"
    markdown_file.write_text(build_markdown_with_summary(PREVIOUS_SUMMARY), encoding="utf-8")

    gh = GithubDependentsInfo("nvuillam/demo", markdown_file=str(markdown_file))
    asyncio.run(gh.maybe_generate_llm_summary())

    assert gh.llm_summary_error == "Insufficient credit balance"
    assert gh.llm_summary == PREVIOUS_SUMMARY
    assert gh.llm_summary_reused is True


def test_summary_reused_is_cached_in_csv_directory(tmp_path, monkeypatch):
    """A summary recovered from markdown is stored in the CSV progress directory"""
    remove_llm_api_keys(monkeypatch)
    markdown_file = tmp_path / "dependents.md"
    markdown_file.write_text(build_markdown_with_summary(PREVIOUS_SUMMARY), encoding="utf-8")
    csv_directory = tmp_path / "csv"
    csv_directory.mkdir()

    gh = GithubDependentsInfo("nvuillam/demo", markdown_file=str(markdown_file), csv_directory=str(csv_directory))
    asyncio.run(gh.maybe_generate_llm_summary())

    assert gh.llm_summary == PREVIOUS_SUMMARY
    cache_files = os.listdir(csv_directory)
    assert any(name.startswith("llm_summary_") for name in cache_files)


def test_no_summary_and_nothing_to_reuse(tmp_path, monkeypatch):
    remove_llm_api_keys(monkeypatch)
    gh = GithubDependentsInfo("nvuillam/demo", markdown_file=str(tmp_path / "unknown.md"))
    asyncio.run(gh.maybe_generate_llm_summary())
    assert gh.llm_summary is None
    assert gh.llm_summary_reused is False
